services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end:task6
    ports:
      - "5252"
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end:task6
    ports:
      - "9000"
    depends_on:
      - back-end
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end